[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm install && node --experimental-strip-types src/index.ts"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
